// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.DifferentialDriveKinematics;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public final class Constants {
    public static final class DriveTrain {
        public static final double WheelDiameterMeters = 0.15;
        public static final int EncoderCPR = 1024;
        public static final double EncoderDistancePerPulse = (WheelDiameterMeters * Math.PI) / (double) EncoderCPR;

        public static final double DefaultSpeedGovernor = 0.5;

        public static final double TrackWidhMeters = 0.69;
        public static final DifferentialDriveKinematics DriveKinematics = new DifferentialDriveKinematics(TrackWidhMeters);

        // THESE VALUES ARE BOGUS AND ONLY HERE FOR SIMULATION. SHOULD NOT BE USED ON LIVE ROBOT
        // Real values should be determined using the Robot Characterization Toolsuite
        public static final double StaticGainVolts = 0.22;
        public static final double VelocityGainVolts = 1.98;
        public static final double AccelerationGainVolts = 0.2;
        public static final double PDriveVelocity = 8.5;

        public static final class SmartDashboard {
            public static final String DriveMode = "Drive Mode";
        }
    }

    public static final class Vision {
        public static final double TargetCameraOffsetMetersX = 1;
        public static final double TargetCameraOffsetMetersY = 1;
        public static final double TargetCameraOffsetMetersZ = 1;
        public static final double TargetCameraRoll = 0;
        public static final double TargetCameraPitch = 0;
        public static final double TargetCameraYaw = Math.PI / 2.0;

        public static final Translation3d TargetCameraPosition =
            new Translation3d(TargetCameraOffsetMetersX, TargetCameraOffsetMetersY, TargetCameraOffsetMetersZ);
        
        public static final Rotation3d TargetCameraRotation =
            new Rotation3d(TargetCameraPitch, TargetCameraRoll, TargetCameraYaw);
        
        public static final Transform3d RobotToTargetCamera = 
            new Transform3d(TargetCameraPosition, TargetCameraRotation);
        
    }

    public static final class Auto {
        public static final double MaxSpeedMetersPerSecond = 3;
        public static final double MaxAccelerationMetersPerSecondSquared = 1;

        public static final double RamseteB = 2;
        public static final double RamseteZ = 0.7;
    }

    public static final class RumblePatterns {
        public static final String ArcadeSplit = "B260:100 P260 B260:100";
        public static final String Arcade1Stick = "B500:100";
        public static final String TankDrive = "L500:75 R500:75";
    }
}
